// Generated by CoffeeScript 1.6.3
(function() {
  var cache, _;

  _ = require('lodash');

  cache = {};

  module.exports.set = function(name, data, expires) {
    var clear;
    if (_.has(cache, name)) {
      clearTimeout(cache[name].timer);
    }
    clear = function() {
      return delete cache[name];
    };
    cache[name] = {
      data: data,
      timer: setTimeout(clear, expires)
    };
    return true;
  };

  module.exports.get = function(name) {
    if (_.has(cache, name)) {
      return cache[name].data;
    } else {
      return null;
    }
  };

}).call(this);
