// Generated by CoffeeScript 1.7.1
(function() {
  var die, done, page, resources, resourcesTimer, system, url, webpage;

  system = require('system');

  webpage = require('webpage');

  url = system.args.slice(-1);

  die = function(message) {
    console.log(message);
    return phantom.exit();
  };

  done = function() {
    var parser;
    parser = function() {
      return document.documentElement.outerHTML.replace(/\<script type="text\/javascript"( (charset|async|data-requirecontext|data-requiremodule|src)="[^"]*")+><\/script>/ig, '');
    };
    return die(page.evaluate(parser));
  };

  if (!url) {
    die("no url supplied\n");
  }

  page = webpage.create();

  page.viewportSize = {
    width: 1024,
    height: 768
  };

  resources = 0;

  resourcesTimer = null;

  page.onResourceRequested = function(request) {
    return resources++;
  };

  page.onResourceReceived = function(response) {
    if (--resources === 0) {
      if (resourcesTimer) {
        clearTimeout(resourcesTimer);
      }
      return resourcesTimer = setTimeout(done, 2500);
    }
  };

  page.open(url, function(status) {
    if (status === "fail") {
      return die("Phantom: could not open url " + url + " \n");
    }
  });

}).call(this);
